### ISSUE TITLE
Sign Up feature is not working 

### ISSUE THREAD

**Issue by NirajSrivastava18** [NJACKWinterOfCode/keep_clone#24]
While clicking on Sign Up it shows a message "Error: The email address is badly formatted.".This message should be shown when the entered email address is wrong.

**Comment by thebishaldeb** [comment]
Screenshot of the error, please.

**Comment by NirajSrivastava18** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/54449124/70505345-c339d380-1b4d-11ea-8370-cb53cfbc4920.png)
