### ISSUE TITLE
"Required"feature in the login page

### ISSUE THREAD

**Issue by NirajSrivastava18** [NJACKWinterOfCode/keep_clone#25]
There should be a Required feature in the login page because if the user does not enter anything in the login page and click on sign in  It should show the "Required" message in the username box and password box and make a red outline box in both boxes.

**Comment by Tanmay211** [comment]
Hey @NirajSrivastava18  ! I would like to work on this issue. May I ?

**Comment by NirajSrivastava18** [comment]
yes, of course, ask the mentor for this thing.

**Comment by thebishaldeb** [comment]
Assigned it to you @Tanmay211

**Comment by Tanmay211** [comment]
Thanx @thebishaldeb !

**Comment by Tanmay211** [comment]
@thebishaldeb Please review my PR and recommend any changes if needed.
