### ISSUE TITLE
Design the card to enter notes.

### ISSUE THREAD

**Issue by ExpressHermes** [NJACKWinterOfCode/keep_clone#3]
The design for inserting notes is pretty basic. Design a card with the title, desc and add button for the homepage.

**Comment by devyaniChoubey** [comment]
I would like to work on this issue. Can I?

**Comment by thebishaldeb** [comment]
Assigned it to you.

**Comment by devyaniChoubey** [comment]
Sir can I bootstrap or materialise css?

**Comment by thebishaldeb** [comment]
Since react-bootstrap is present in the package.json, you can use both according to your convenience.

Also I'm a college student. Don't call me sir. Lol.

**Comment by devyaniChoubey** [comment]
okk   Sorry

**Comment by devyaniChoubey** [comment]
I have to edit the form????
I thought I have to design the card to display notes.

**Comment by thebishaldeb** [comment]
Yeah, it was for the form part. 
Though I merged it and gave you points, but you had to make that form a modal actually. 
The notes cards need to be present on the page and not in a modal.
You can work on that now.

**Comment by devyaniChoubey** [comment]
Sorry. I will fix it

> Yeah, it was for the form part.
> Though I merged it and gave you points, but you had to make that form a modal actually.
> The notes cards need to be present on the page and not in a modal.
> You can work on that now.
Sorry. I will fix it today

**Comment by devyaniChoubey** [comment]
Sorry , I will fix today

**Comment by devyaniChoubey** [comment]
Sorry, I will fix it

**Comment by thebishaldeb** [comment]
@devyaniChoubey update? Your prev PR had bugs and now the notes cannot be editted. Please resolve them, otherwise will have to revert the PR.

**Comment by devyaniChoubey** [comment]
ok, I will try to fix it

**Comment by thebishaldeb** [comment]
@devyaniChoubey  update?
