### ISSUE TITLE
Edit Features of the notes.

### ISSUE THREAD

**Issue by ExpressHermes** [NJACKWinterOfCode/keep_clone#5]
**Is your feature request related to a problem? Please describe.**
Currently a user cannot edit the notes.

**Describe the solution you'd like**
Make a provision for that by clicking a button in the notes

**Comment by dev-sankhadip** [comment]
Can i work on this one?

**Comment by thebishaldeb** [comment]
> Can i work on this one?

Sure.

**Comment by dev-sankhadip** [comment]
Do i need to edit both title and description?

**Comment by thebishaldeb** [comment]
> Do i need to edit both title and description?

Yeah. Since there are three options in the form - text, list and draw, it should be rendered accordingly.

**Comment by dev-sankhadip** [comment]
Ok sir i will look on it...

**Comment by dev-sankhadip** [comment]
can i make another component for editing?

**Comment by thebishaldeb** [comment]
Okay. You may use whatever is convenient.

**Comment by dev-sankhadip** [comment]
I am having exam that's why i paused it, on Friday once my exam finished i will resume it.

**Comment by dev-sankhadip** [comment]
I have created pull request of this issue,can you please check out?
