### ISSUE TITLE
Fix remove/delete icon for each note

### ISSUE THREAD

**Issue by nandhini-sr** [NJACKWinterOfCode/keep_clone#9]
**Describe the bug**
A note cannot be deleted by clicking remove icon on each note 

**To Reproduce**
1. Create a new note
2. Click on remove X icon
3. See error: this.props.removeNote is not a function

**Expected behavior**
Each note must deleted on clicking the remove icon

**Comment by dev-sankhadip** [comment]
I would like to work on this issue,can i?

**Comment by thebishaldeb** [comment]
@labyrinth-maven are you working on it?

@dev-sankhadip I guess she was working on it.

**Comment by dev-sankhadip** [comment]
I have solved the problem,can i create pull request for your review?

**Comment by thebishaldeb** [comment]
Okay sure then.

**Comment by dev-sankhadip** [comment]
ok sir..
